✨ Added docstrings to `pyfiction`
cda-tum/fiction pull request #187
Opened 2023-04-18 12:51 UTC by simon1hofmann

## Description

- Added workflow to collect all docstrings from `fiction`, which are then uploaded as an artifact.
- Added docstrings to python bindings

## Checklist:

- [x] The pull request only contains commits that are related to it.
- [x] I have added appropriate tests and documentation.
- [x] I have made sure that all CI jobs on GitHub pass.
- [x] The pull request introduces no new warnings and follows the project's style guidelines.

2023-04-18 13:20 UTC, marcelwa requested changes

2023-04-18 13:20 UTC, marcelwa commented on .github/workflows/python_collect_docstrings.yml
> +          python-version: "3.11.x"
You can enable dependency caching via `cache: 'pip'` in the `with:` scope

2023-04-18 13:20 UTC, marcelwa commented on .github/workflows/python_collect_docstrings.yml
> +        run: python3 -m pybind11_mkdoc -o ${{github.workspace}}/docstrings.h `find ${{github.workspace}}/include/fiction -name "*.hpp" -print`
Since we use the `.hpp` header extension, can `docstrings` please also use it for consistency?

2023-04-18 13:20 UTC, marcelwa commented on .github/workflows/python_collect_docstrings.yml
> +    runs-on: macos-latest
Can we run the action on `ubuntu-latest` instead? Usually, there are more Ubuntu runners available, which gives this workflow a better response time

2023-04-18 14:44 UTC, marcelwa requested changes
Looks really good. Many thanks! Just some consistency requests from my end.

2023-04-18 14:44 UTC, marcelwa commented on bindings/pyfiction/include/pyfiction/algorithms/verification/design_rule_violations.hpp
> +        DOC(fiction_detail_gate_level_drvs_impl));
I might be mistaken, but isn't this the wrong docstring? Shouldn't it be something like `fiction_gate_level_drvs`?

2023-04-18 14:44 UTC, marcelwa commented on bindings/pyfiction/include/pyfiction/algorithms/verification/design_rule_violations.hpp
> +                       DOC(fiction_detail_gate_level_drvs_impl_unplaced_nodes_check))
For all these attributes, the docstring is referring to the functions inside the `detail` namespace, but not the `gate_level_drv_params` attributes, or?

2023-04-18 14:44 UTC, marcelwa commented on bindings/pyfiction/include/pyfiction/algorithms/verification/design_rule_violations.hpp
>      py::class_<fiction::gate_level_drv_params>(m, "gate_level_drv_params")
This struct does not yet have a docstring, right?

2023-04-18 14:44 UTC, marcelwa commented on bindings/pyfiction/include/pyfiction/layouts/hexagonal_layout.hpp
>          .def(py::init<>())
As above: no docstring available for the constructors?

2023-04-18 14:44 UTC, marcelwa commented on bindings/pyfiction/include/pyfiction/layouts/obstruction_layout.hpp
>          .def("obstruct_coordinate", &ObstrLyt::obstruct_coordinate, "c"_a)
Don't we have docstrings for these member functions?

2023-04-19 07:00 UTC, simon1hofmann commented on bindings/pyfiction/include/pyfiction/io/write_qcc_layout.hpp
> +        "layout"_a, "filename"_a, DOC(fiction_write_qca_layout));
Yes, I think the name of the function is wrong: `write_qca_layout`.

2023-04-19 07:17 UTC, marcelwa commented on bindings/pyfiction/include/pyfiction/io/write_qcc_layout.hpp
> +        "layout"_a, "filename"_a, DOC(fiction_write_qca_layout));
Good catch! Could you then also please adjust the function name?

2023-04-19 09:12 UTC, marcelwa approved these changes

2023-04-19 09:12 UTC, merged