:art: Allow fiction coordinates for simulation and other functions.
cda-tum/fiction pull request #336
Opened 2023-11-21 21:13 UTC by Drewniok

## Description

This PR makes it possible to use fiction coordinates for simulation.

## Checklist:

- [x] The pull request only contains commits that are related to it.
- [x] I have added appropriate tests and documentation.
- [ ] I have made sure that all CI jobs on GitHub pass.
- [ ] The pull request introduces no new warnings and follows the project's style guidelines.

2023-11-24 12:02 UTC, marcelwa requested changes
Many thanks for the thorough changes. I have only a few comments.

2023-11-24 12:02 UTC, marcelwa commented on include/fiction/utils/layout_utils.hpp
> +[[nodiscard]] inline std::vector<CoordinateType> all_sidbs_in_spanned_area(const CoordinateType& cell_nw,
This function doesn't require SiDBs anywhere. Can we maybe change its name to reflect that?

2023-11-24 12:02 UTC, marcelwa commented on include/fiction/utils/layout_utils.hpp
>   * @param cell_se The southeast SiQAD cell defining the ending point of the area.
There are still some SiQAD namings in the comments here. Maybe do a quick CTRL + SHIFT + F for "siqad" across the project to see what else there is to replace.

2023-11-24 12:02 UTC, marcelwa commented on include/fiction/utils/layout_utils.hpp
> +    // for siqad coordinates
I noticed inconsistent usage of "siqad" vs. "SiQAD" in comments. In the code, we have naming conventions of course. In the comments, we should be able to call the tool by its original spelling, no?

2023-11-24 12:04 UTC, Drewniok commented on include/fiction/algorithms/simulation/sidb/quickexact.hpp
> +                        charge_distribution_surface charge_layout{static_cast<Lyt>(layout)};
@marcelwa If I recall correctly, it is required for the Windows CIs to pass.

2023-11-24 12:05 UTC, Drewniok commented on include/fiction/layouts/bounding_box.hpp
> +            uint8_t min_z = 1;
@marcelwa bug fix

2023-11-24 14:08 UTC, Drewniok commented on include/fiction/technology/sidb_nm_position.hpp
>  }
Wow! That's wonderful!

2023-11-24 15:23 UTC, Drewniok commented on include/fiction/technology/sidb_nm_position.hpp
>  }
@marcelwa Unfortunately, it does not work.

2023-11-27 10:35 UTC, marcelwa approved these changes

2023-11-27 12:01 UTC, merged