🚧 Si-111 surface support
cda-tum/fiction pull request #380
Opened 2024-02-12 08:03 UTC by Drewniok

## Description

This PR adds support for the physical design and simulation for the Si-111 surface.

## Checklist:

- [x] The pull request only contains commits that are related to it.
- [x] I have added appropriate tests and documentation.
- [ ] I have made sure that all CI jobs on GitHub pass.
- [ ] The pull request introduces no new warnings and follows the project's style guidelines.

2024-03-25 08:06 UTC, marcelwa requested changes
Many thanks for your hard work on this! There are couple of open points. This review is not complete yet, but I hope it helps you already.

2024-03-25 11:50 UTC, Drewniok commented on include/fiction/technology/sidb_surface.hpp
That's a good idea, and I've often thought about it because it's very confusing.

2024-03-25 12:06 UTC, Drewniok commented on include/fiction/traits.hpp
> +struct is_sidb_lattice<Lyt, std::void_t<typename Lyt::orientation>> : std::true_type
@marcelwa Can you please explain again what you mean by this?

2024-03-25 12:19 UTC, Drewniok commented on include/fiction/technology/sidb_lattice_types.hpp
> +struct sidb_100_lattice
@marcelwa That's a good point! I will also delete the ``Copy Constructor`` and the ``Copy Assignment Operator``, right?

2024-03-25 12:47 UTC, Drewniok commented on include/fiction/technology/sidb_nm_position.hpp
> +        return {};
@marcelwa do you mean to replace the ``assert`` by ``static_assert(!is_sidb_lattice_100_v<Lyt> && !is_sidb_lattice_111_v<Lyt> && "Unknown lattice orientation")``?

2024-03-25 12:52 UTC, Drewniok commented on include/fiction/technology/sidb_nm_position.hpp
> +        return {};
or do you mean something like this here: 
```c++
    if constexpr (!is_sidb_lattice_100_v<Lyt> && !is_sidb_lattice_111_v<Lyt>)
    {
        return {};
    }
```

2024-03-25 13:10 UTC, marcelwa commented on include/fiction/technology/sidb_lattice_types.hpp
> +struct sidb_100_lattice
You can do that, but it’s not required. If it cannot be instantiated, it can also not be copied or assigned.

2024-03-25 13:11 UTC, marcelwa commented on include/fiction/technology/sidb_nm_position.hpp
> +        return {};
> @marcelwa do you mean to replace the `assert` by `static_assert(!is_sidb_lattice_100_v<Lyt> && !is_sidb_lattice_111_v<Lyt> && "Unknown lattice orientation")`?

More like `static_assert(is_sidb_lattice_100_v<Lyt> || is_sidb_lattice_111_v<Lyt>,  "Unsupported lattice orientation")`

2024-03-25 13:44 UTC, Drewniok commented on include/fiction/technology/sidb_lattice.hpp
> +template <typename Lyt, typename LatticeOrientation = sidb_100_lattice>
great idea! You are absolutely right.

2024-03-25 14:40 UTC, Drewniok commented on include/fiction/technology/sidb_lattice.hpp
> +template <typename Lyt, typename LatticeOrientation = sidb_100_lattice>
@marcelwa But I guess I'm then struggling to use a default value for the lattice orientation, which is quite convenient so far, right?

2024-03-25 15:05 UTC, marcelwa commented on include/fiction/technology/sidb_lattice.hpp
> +template <typename Lyt, typename LatticeOrientation = sidb_100_lattice>
For the constructor of `sidb_lattice`, that is absolutely true. However, we should think about how much it makes sense to have the lattice be a default anyway. If you're assigning a lattice manually, you obviously want to achieve a certain task. Thereby, you might want to specify it anyway. Same with `cell_level_layout`. I'd have a problem with `qca_technology` being the default, for instance.

2024-03-26 07:35 UTC, Drewniok commented on include/fiction/utils/layout_utils.hpp
> +        return process_layout(lyt_new);
This only works if we don't use a reference as input to the lambda expression.

2024-03-26 07:53 UTC, Drewniok commented on include/fiction/utils/truth_table_utils.hpp
I am aware of this, but it is sometimes difficult to avoid, especially since we still have this issue with #PR317.

2024-03-26 09:40 UTC, Drewniok commented on include/fiction/algorithms/simulation/sidb/determine_the_groundstate_from_simulation_results.hpp
> + * @return A vector of charge distributions with the minimal energy.
Yes, if the ground state is degenerated, we return two CDSs.

2024-03-26 10:01 UTC, Drewniok commented on include/fiction/algorithms/simulation/sidb/determine_the_groundstate_from_simulation_results.hpp
I don't think we have this function yet.

2024-03-26 10:14 UTC, Drewniok commented on include/fiction/algorithms/simulation/sidb/determine_the_groundstate_from_simulation_results.hpp
> +    std::set<uint64_t>                            charge_indices{};
@marcelwa Have you ever used it? I get some weird errors.

2024-03-26 14:13 UTC, Drewniok commented on include/fiction/io/print_layout.hpp
> +                break;
it has an influence on the result.

2024-03-26 14:26 UTC, Drewniok commented on include/fiction/io/read_sqd_layout.hpp
> +    static_assert(is_sidb_lattice_v<Lyt>, "Lyt must be a lattice layout");
@marcelwa The idea was that a grid orientation is used and if the read grid orientation does not match, an exception is thrown. What do you hink about this?

2024-03-27 07:09 UTC, Drewniok commented on include/fiction/io/read_sqd_layout.hpp
> +    static_assert(is_sidb_lattice_v<Lyt>, "Lyt must be a lattice layout");
For the this function, I would leave it as it is. What do you think?

2024-03-27 13:01 UTC, Drewniok commented
@marcelwa I have made some major changes. I hope it looks better now. Thank you for your feedback! 🙏

2024-03-27 15:18 UTC, marcelwa commented
The name of this PR refers to (111)-2x1 currently. Shouldn't it be (111)-1x1?

2024-03-27 15:20 UTC, Drewniok commented
> The name of this PR refers to (111)-2x1 currently. Shouldn't it be (111)-1x1?

oh, you are right! Thank you!

2024-04-04 13:24 UTC, marcelwa requested changes
Many, many thanks for your enormous effort with this PR! :pray: I have no further architectural complaints. Everything looks good to me. My comments are mostly very minor.

2024-04-04 13:24 UTC, marcelwa commented on test/technology/charge_distribution_surface.cpp
> +    //    }
What is up with this commented-out code?

2024-04-04 13:24 UTC, marcelwa commented on test/technology/charge_distribution_surface.cpp
We probably want some 111 tests here, no?

2024-04-04 13:24 UTC, marcelwa commented on test/technology/sidb_defect_surface.cpp
> +    SECTION("With SiDB lattice")
Test both lattices?

2024-04-04 13:24 UTC, marcelwa commented on test/technology/sidb_lattice.cpp
> +    CHECK(is_sidb_lattice_111_v<lattice_on_lattice>);
This should not compile in my opinion. It is a design decision obviously. Maybe we can ponder this question together. If you have a 111 surface already and you try to layer a 100 on top, that might indicate a problem with your code. That's my reasoning behind why I think it should not compile.

2024-04-04 13:24 UTC, marcelwa commented on test/technology/sidb_lattice.cpp
> +    lyt_111.assign_cell_type({5, 0}, sidb_100_cell_clk_lyt::cell_type::NORMAL);
```suggestion
    lyt_111.assign_cell_type({0, 0}, sidb_111_cell_clk_lyt::cell_type::NORMAL);
    lyt_111.assign_cell_type({3, 0}, sidb_111_cell_clk_lyt::cell_type::NORMAL);
    lyt_111.assign_cell_type({5, 0}, sidb_111_cell_clk_lyt::cell_type::NORMAL);
```

2024-04-04 13:24 UTC, marcelwa commented on cli/cmd/simulation/quicksim.hpp
> +                        sim_result = fiction::quicksim(*lyt_ptr, params);
Rename the variable to `sim_result_100`?

2024-04-04 13:24 UTC, marcelwa commented on cli/cmd/simulation/quicksim.hpp
> +    fiction::sidb_simulation_result<fiction::sidb_111_cell_clk_lyt> sim_result_111{};
Due to an `alice` bug, you might need to reset both of these variables to empty states every time before the function returns.

2024-04-04 13:24 UTC, marcelwa commented on cli/cmd/simulation/quicksim.hpp
> +    fiction::sidb_simulation_result<fiction::sidb_111_cell_clk_lyt> sim_result_111{};
Otherwise, they get stuck with their respective values between calls

2024-04-04 13:24 UTC, marcelwa commented on experiments/random_sidb_layout_generation/random_sidb_layout_generation.cpp
> +                std::cerr << fmt::format("Error: Argument {} is missing a value", arg) << '\n';
```suggestion
                std::cerr << fmt::format("Error: Argument {} is missing a value\n", arg);
```

2024-04-04 13:24 UTC, marcelwa commented on experiments/random_sidb_layout_generation/random_sidb_layout_generation.cpp
> +    std::cout << fmt::format("step: ", step) << '\n';
see above for line endings

2024-04-04 13:24 UTC, marcelwa commented on experiments/random_sidb_layout_generation/sidb_location_and_ground_state_simulation.cpp
> +                std::cerr << "Error: Argument " << arg << " is missing a value." << '\n';
Use `fmt::format`

2024-04-04 13:24 UTC, marcelwa commented on experiments/random_sidb_layout_generation/sidb_location_and_ground_state_simulation.cpp
> +    std::cout << fmt::format("µ_minus: {}", mu) << '\n';
see above

2024-04-04 14:05 UTC, Drewniok commented on include/fiction/traits.hpp
> +inline constexpr const bool has_same_lattice_orientation_v =
@marcelwa Good point! Should we maybe call it ``has_given_lattice_orientation_v``?

2024-04-04 14:07 UTC, marcelwa commented on include/fiction/traits.hpp
> +inline constexpr const bool has_same_lattice_orientation_v =
That sounds great! :)

2024-04-04 14:19 UTC, Drewniok commented on docs/index.rst
> +   technology/sidb_lattice_orientations.rst
@marcelwa ah, I have just realized that the ``sidb_defect_surface`` is part of ``defects.rst``. Should I delete this file here?

2024-04-04 14:52 UTC, Drewniok commented on include/fiction/algorithms/simulation/sidb/is_operational.hpp
> +[[nodiscard]] std::size_t number_of_operational_inputs(const Lyt& lyt, const std::vector<TT>& spec,
@marcelwa This means that we don't need ``stats`` anymore, because the operational input combinations are stored there?

2024-04-04 14:59 UTC, marcelwa commented on include/fiction/algorithms/simulation/sidb/is_operational.hpp
> +[[nodiscard]] std::size_t number_of_operational_inputs(const Lyt& lyt, const std::vector<TT>& spec,
Correct

2024-04-04 17:26 UTC, Drewniok commented on include/fiction/types.hpp
> +                 sidb_111_cell_clk_lyt_ptr, cds_sidb_100_cell_clk_lyt_ptr, cds_sidb_111_cell_clk_lyt_ptr>;
I would say they are all useful, especially for unit testing.

2024-04-05 08:49 UTC, Drewniok commented
> Many, many thanks for your enormous effort with this PR! 🙏 I have no further architectural complaints. Everything looks good to me. My comments are mostly very minor.

@marcelwa Many, many thanks for your detailed and helpful review! I have tried to address all of them. I also added more unit tests.

2024-04-05 10:40 UTC, marcelwa commented on cli/cmd/simulation/quickexact.hpp
> +        sim_result_100 = {};
Why not reset both?

2024-04-05 10:40 UTC, marcelwa commented on cli/cmd/simulation/quicksim.hpp
> +        sim_result_100 = {};
Why not reset both?

2024-04-05 11:00 UTC, marcelwa requested changes

2024-04-05 11:00 UTC, marcelwa commented on include/fiction/algorithms/simulation/sidb/is_operational.hpp
> +                                                              const is_operational_params& params = {}) noexcept
Given the new return type, this function seems misnamed now. It should rather be something like `operational_input_patterns`

2024-04-05 11:00 UTC, marcelwa commented on include/fiction/algorithms/simulation/sidb/is_operational.hpp
> +    [[nodiscard]] std::set<uint64_t> count_number_of_operational_inputs() noexcept
Why is this called `count_*` when it returns an `std::set` instead of a number?

2024-04-05 11:00 UTC, marcelwa commented on include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
> +     * simulation results are stored in the `sim_result_100` variable.
Was this renaming intended?

2024-04-05 11:00 UTC, marcelwa commented on include/fiction/algorithms/simulation/sidb/is_operational.hpp
> +     * simulation results are stored in the `sim_result_100` variable.
Was this renaming intended?

2024-04-05 11:00 UTC, marcelwa commented on include/fiction/algorithms/simulation/sidb/determine_groundstate_from_simulation_results.hpp
> +    for (auto& cds : charge_configurations_copy)
Not sure, but can this be `const`? The functions you call on `cds` sound like they could be all `const`.

2024-04-05 11:00 UTC, marcelwa commented on include/fiction/utils/layout_utils.hpp
> + * migration of SiDB defects if they exist.
Given this explanation, it does not seem like this function is doing a lot of computation, it is just copying data around, is that correct? If so, that seems to be the job of a copy-constructor/copy-assignment operator.

2024-04-05 11:05 UTC, Drewniok commented on include/fiction/algorithms/simulation/sidb/is_operational.hpp
> +     * simulation results are stored in the `sim_result_100` variable.
Sorry, that's a mistake.

2024-04-05 13:03 UTC, marcelwa requested changes
Perfect, we are essentially done. There is just this one typo.

2024-04-05 13:03 UTC, marcelwa commented on include/fiction/algorithms/simulation/sidb/is_operational.hpp
> +    [[nodiscard]] std::set<uint64_t> determine_operational_input_pattern() noexcept
```suggestion
    [[nodiscard]] std::set<uint64_t> determine_operational_input_patterns() noexcept
```

2024-04-05 13:10 UTC, marcelwa approved these changes
Many, many thanks for your hard work! :pray:

2024-04-05 15:42 UTC, merged