🐛 Multi-output nodes
cda-tum/fiction pull request #451
Opened 2024-06-04 07:59 UTC by simon1hofmann

## Description

Fixes a corner case in `ortho` where a gate has multiple output nodes connected to it.
Thanks to @hibenj for pointing out this solution in his implementation of `orthogonal_ordering_network`.

## Checklist:

- [ ] The pull request only contains commits that are related to it.
- [ ] I have added appropriate tests and documentation.
- [ ] I have added a changelog entry.
- [ ] I have created/adjusted the Python bindings for any new or updated functionality.
- [ ] I have made sure that all CI jobs on GitHub pass.
- [ ] The pull request introduces no new warnings and follows the project's style guidelines.

2024-06-04 08:22 UTC, hibenj commented
The code seems to be working. Before merging you might test the following: I guess you already checked for all benchmarks, that this is working. But you could also check, if the number of added rows corresponds to the number of multi PO nodes. But since you first determine the layout size and then insert the PO nodes, everything should be working perfectly. I just know i had issues with this before.

2024-06-04 08:25 UTC, simon1hofmann commented
> The code seems to be working. Before merging you might test the following: I guess you already checked for all benchmarks, that this is working. But you could also check, if the number of added rows corresponds to the number of multi PO nodes. But since you first determine the layout size and then insert the PO nodes, everything should be working perfectly. I just know i had issues with this before.

Additional rows are added based on the number of multi-output nodes in `determine_layout_size()`:

`// for multi-output nodes, add another row
    y += num_multi_output_pos;`

2024-06-04 08:27 UTC, hibenj reviewed
The code seems to be working. But since you already iterate through all pos at the beginning of orthogonal_impl adn therefore compute all multi_out_nodes, you might be able to use them in the main loop of ortho to place the multi_out_nodes. With this implementation you need to iterate through all pos twice.
So i approved it, since its working, but i guess its up to @marcelwa if this implementation makes sense.

2024-06-04 08:29 UTC, hibenj submitted a review, later dismissed

2024-06-06 07:30 UTC, simon1hofmann commented
> The code seems to be working. But since you already iterate through all pos at the beginning of orthogonal_impl and therefore compute all multi_out_nodes, you might be able to use them in the main loop of ortho to place the multi_out_nodes. With this implementation you need to iterate through all pos twice. So i approved it, since its working, but i guess its up to @marcelwa if this implementation makes sense.

The problem ist that multi-output POs usually appear in a different order in `foreach_po` compared to `foreach_node`.
I now added a check for the appearance of multi-output POs in the network and only if they are present, the POs are placed after the main loop. Otherwise, `ortho` places all POs in the main loop.

2024-06-06 08:06 UTC, simon1hofmann commented
> > The code seems to be working. But since you already iterate through all pos at the beginning of orthogonal_impl and therefore compute all multi_out_nodes, you might be able to use them in the main loop of ortho to place the multi_out_nodes. With this implementation you need to iterate through all pos twice. So i approved it, since its working, but i guess its up to @marcelwa if this implementation makes sense.
> 
> The problem ist that multi-output POs usually appear in a different order in `foreach_po` compared to `foreach_node`. I now added a check for the appearance of multi-output POs in the network and only if they are present, the POs are placed after the main loop. Otherwise, `ortho` places all POs in the main loop.

Actually, this can also happen for networks without mulit-ouput POs, which explains why the layout for `clpl` was not equivalent. I added another check to test that.

2024-07-05 12:04 UTC, marcelwa requested changes

2024-07-05 12:04 UTC, marcelwa commented on include/fiction/algorithms/physical_design/orthogonal.hpp
> +                                ++latest_pos.x;
Instead of manually incrementing x and y positions, rather use `east()` and `south()`

2024-07-05 12:04 UTC, marcelwa commented on include/fiction/algorithms/physical_design/orthogonal.hpp
> +                                ++latest_pos.y;
here too

2024-07-05 12:04 UTC, marcelwa commented on include/fiction/algorithms/physical_design/orthogonal.hpp
> +                                ++latest_pos.y;
here too

2024-07-15 17:34 UTC, simon1hofmann commented
@marcelwa I refactored the code to always place POs at the end, as this will solve both problems simultaneously.

2024-07-17 10:37 UTC, marcelwa requested changes
Just two tiny comments, then it is ready to be merged

2024-07-17 10:37 UTC, marcelwa commented on include/fiction/algorithms/physical_design/orthogonal.hpp
> +                   mockturtle::node_map<mockturtle::signal<Lyt>, decltype(ctn.color_ntk)>& node2pos)
If `node2pos` is not updated, it may be `const`

2024-07-17 10:37 UTC, marcelwa commented on include/fiction/algorithms/physical_design/orthogonal.hpp
> +        // Find multi_output_nodes
```suggestion
        // find multi-output nodes
```

2024-07-17 13:31 UTC, merged