✨ Extended BDL input iterator to support different SiDB input representations
cda-tum/fiction pull request #521
Opened 2024-09-03 14:26 UTC by Drewniok

## Description

This PR enhances the _BDL input iterator_ to accommodate the varying ways input information can be implemented in SiDB technology. In some cases, such as with Bestagon gates, the binary value `0` may be represented by a perturber placed farther away compared to the `1` state. In contrast, _SiQAD_ gates typically represent `0` by the absence of a perturber and `1` by the presence of a perturber.

In addition, this PR includes the missing experiment scripts needed for temperature simulation.

## Checklist:

- [ ] The pull request only contains commits that are related to it.
- [ ] I have added appropriate tests and documentation.
- [ ] I have added a changelog entry.
- [ ] I have created/adjusted the Python bindings for any new or updated functionality.
- [ ] I have made sure that all CI jobs on GitHub pass.
- [ ] The pull request introduces no new warnings and follows the project's style guidelines.

2024-09-05 15:21 UTC, marcelwa commented on include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
@Drewniok this is actually meaningful.

2024-09-05 15:21 UTC, marcelwa commented on cli/cmd/simulation/temp.hpp
> +    double ct = 0.0;
Maybe you want to reset this value in the beginning of the `execute` function

2024-09-05 15:21 UTC, marcelwa commented on include/fiction/algorithms/iter/bdl_input_iterator.hpp
> +     *    by positioning the perturber farther away (as described in https://dl.acm.org/doi/10.1145/3489517.3530525).
```suggestion
     * 1. A perturber is used to set the input to `1`, while the absence of a perturber represents a `0`
     *    (as described in https://ieeexplore.ieee.org/abstract/document/8963859).
     * 2. An input of `1` is generated by placing a perturber closer to the target, whereas a `0` is produced
     *    by positioning the perturber farther away (as described in https://dl.acm.org/doi/10.1145/3489517.3530525).
```

2024-09-05 15:21 UTC, marcelwa commented on include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
> +    uint64_t maximal_attempts_for_multiple_layouts = 1000000;
```suggestion
    uint64_t maximal_attempts_for_multiple_layouts = 1'000'000;
```

2024-09-06 10:32 UTC, marcelwa commented
@Drewniok can you still add a CHANGELOG entry, please?

2024-09-06 11:15 UTC, Drewniok commented
> @Drewniok can you still add a CHANGELOG entry, please?

Done!

2024-09-06 11:16 UTC, marcelwa requested changes

2024-09-06 11:16 UTC, marcelwa commented on docs/changelog.rst
> +v0.6.5 - 2024-09-06
```suggestion
Unreleased```

2024-09-06 11:33 UTC, marcelwa approved these changes

2024-09-07 05:11 UTC, merged